/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoanalisis2017.pkg1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.ImageIcon;

/**
 *
 * @author Gianka
 */
public class pnlVentana extends javax.swing.JPanel implements KeyListener{

    /**
     * Creates new form pnlCiudad
     */
    private int x1Ciudad;
    private int x2Ciudad;
    private int x1Componente;
    private int x2Componete;
    private int altura;
    Ciudad ciudad;
    private Boolean estaSelecionadoComponente;
    
    LinkedList<Item> lstItems;
    
  
    private Item itemSeleccionado;
    private int xImgSelecionada;
    private int yImgSelecionada;

    public pnlVentana() {
        initComponents();
        
        this.lstItems = new LinkedList<>();
        this.xImgSelecionada = 0;
        this.yImgSelecionada = 0;
        this.itemSeleccionado = new Item();
        this.estaSelecionadoComponente = false;
        //crearComponentes();
        // crearComponentes();        
        //this.setBackground(Color.BLACK);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        if (evt.getX() > this.x1Componente && evt.getX() < this.x2Componete) {
            for (int i = 0; i < this.lstItems.size(); i++) {
                if (this.lstItems.get(i).area.contains(new Point(evt.getX(), evt.getY()))) {
                    this.estaSelecionadoComponente = true;
                    this.lstItems.get(i).contador=0;
                    this.itemSeleccionado = this.lstItems.get(i);
                }
            }
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (this.estaSelecionadoComponente) {

            this.xImgSelecionada = evt.getX();
            this.yImgSelecionada = evt.getY();
            repaint();
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (this.estaSelecionadoComponente) {
            try {

                this.estaSelecionadoComponente = false;
                this.xImgSelecionada = 0;
                this.yImgSelecionada = 0;
                int auxN = evt.getY() / this.ciudad.altoCampo;
                int auxM = evt.getX() / this.ciudad.anchoCampo;
                this.ciudad.matrizCiudad[auxN][auxM] = this.itemSeleccionado.lstComponentes.get(this.itemSeleccionado.contador).tipo;
                //this.tipoSeleccionado = new c;///__________________________________________________________asAsdasd

            } catch (Exception e) {

            }
            repaint();
        }
    }//GEN-LAST:event_formMouseReleased

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyPressed
    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        System.out.println((x2Ciudad));
        g.drawImage(new ImageIcon(getClass().getResource("../ImgComponentes/Fondo.jpg")).getImage(), 0, 0, this.x2Ciudad, this.altura, this);
        g.setColor(Color.decode("#FC4600"));
        g.fillRect(this.x1Componente, 0, (this.x2Componete - this.x2Ciudad) * 2, this.altura);
        g.setColor(Color.BLACK);
        pintarComponentes(g);
        if (ciudad != null) {
            // lineas de referencia de las areas de la aplicacion
            g.drawRect(0, 0, this.x2Ciudad, this.altura);
            //g.setColor(Color.red);
            // g.drawRect(this.x1Componente, 0, this.x2Componete - this.x1Componente, this.altura);
            //------Pintar componentes--------

            pintarCiudad(g);

            //pinta la anamiacion de colocar imagen en el tablero
            if (this.estaSelecionadoComponente && this.xImgSelecionada > this.x1Ciudad && this.xImgSelecionada < this.x2Ciudad && this.yImgSelecionada > 0 && this.yImgSelecionada < this.altura) {

                g.drawImage(new ImageIcon(getClass().getResource(this.itemSeleccionado.lstComponentes.get(this.itemSeleccionado.contador).ruta)).getImage(), this.xImgSelecionada, this.yImgSelecionada, 100, 100, this);
                int auxN = this.yImgSelecionada / this.ciudad.altoCampo;
                int auxM = this.xImgSelecionada / this.ciudad.anchoCampo;
                System.out.println(auxN + "--" + auxM);
                g.drawRect(auxM * this.ciudad.anchoCampo, auxN * this.ciudad.altoCampo, this.ciudad.anchoCampo, this.ciudad.altoCampo);
            }
        }
    }

    public void crearComponentes() {
        int auxAltura = 100;
        //this.lstComponente.add(new Item(this.idContador++, "4.1", "../ImgComponentes/4.1.png", ));
        LinkedList<Componente> auxLista= new LinkedList<>();
        auxLista.add(new Componente("4.1"));
        auxLista.add(new Componente("4.2"));
        auxLista.add(new Componente("4.3"));
        auxLista.add(new Componente("4.4"));
  
        this.lstItems.add(new Item(0, auxLista, this.x1Componente + 20, 0 * auxAltura, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("1.1"));
        auxLista.add(new Componente("1.2"));
        this.lstItems.add(new Item(1, auxLista, this.x1Componente + 20, 1 * auxAltura+10, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("2.1"));
        auxLista.add(new Componente("2.2"));
        auxLista.add(new Componente("2.3"));
        auxLista.add(new Componente("2.4"));
        this.lstItems.add(new Item(2, auxLista, this.x1Componente + 20, 2 * auxAltura+20, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("3.1"));
        auxLista.add(new Componente("3.2"));
        this.lstItems.add(new Item(3, auxLista, this.x1Componente + 20, 3 * auxAltura+30, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("5.1"));
        auxLista.add(new Componente("5.2"));
        auxLista.add(new Componente("5.3"));
        auxLista.add(new Componente("5.4"));
        this.lstItems.add(new Item(4, auxLista, this.x1Componente + 20, 4 * auxAltura+40, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("6.1"));
        auxLista.add(new Componente("6.2"));
        auxLista.add(new Componente("6.3"));
        auxLista.add(new Componente("6.4"));
        this.lstItems.add(new Item(4, auxLista, this.x1Componente + 20, 5 * auxAltura+50, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("7.1"));
        auxLista.add(new Componente("7.2"));
        auxLista.add(new Componente("7.3"));
        auxLista.add(new Componente("7.4"));
        this.lstItems.add(new Item(6, auxLista, this.x1Componente + 20+80, 0 * auxAltura, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("8.1"));
        auxLista.add(new Componente("8.2"));
        auxLista.add(new Componente("8.3"));
        auxLista.add(new Componente("8.4"));
        this.lstItems.add(new Item(7, auxLista, this.x1Componente + 30+80, 1 * auxAltura, 70, 100));
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("9.1"));
        auxLista.add(new Componente("9.2"));
        auxLista.add(new Componente("9.3"));
        auxLista.add(new Componente("9.4"));
        this.lstItems.add(new Item(8, auxLista, this.x1Componente + 30+80, 2 * auxAltura, 70, 100));
       
        auxLista= new LinkedList<>();
        auxLista.add(new Componente("11.1"));
        auxLista.add(new Componente("11.2"));
        auxLista.add(new Componente("11.3"));
        auxLista.add(new Componente("11.4"));
        this.lstItems.add(new Item(9, auxLista, this.x1Componente + 30+80, 3 * auxAltura, 70, 100));
// this.lstComponente.add(new Item(this.idContador++, 2, "../ImgComponentes/2.png", this.x1Componente + 20, this.idContador * auxAltura, 100, auxAltura));
        //this.lstComponente.add(new Item(this.idContador++, 3, "../ImgComponentes/3.png", this.x1Componente + 20, this.idContador * auxAltura, 100, auxAltura));
        //this.lstComponentipote.add(new Item(this.idContador++, 4, "../ImgComponentes/4.png", this.x1Componente + 20, this.idContador * auxAltura, 100, auxAltura));
        //this.lstComponente.add(new Item(this.idContador++, 0, "../ImgComponentes/0.png", this.x1Componente + 20, this.idContador * auxAltura, 100, auxAltura));

    }

    public void setX1Ciudad(int x1Ciudad) {
        this.x1Ciudad = x1Ciudad;
    }

    public void setX2Ciudad(int x2Ciudad) {
        this.x2Ciudad = x2Ciudad;
    }

    public void setX1Componente(int x1Componente) {
        this.x1Componente = x1Componente;
    }

    public void setX2Componete(int x2Componete) {
        this.x2Componete = x2Componete;
    }

    public void setAltura(int altura) {
        this.altura = altura;
    }

    private void pintarComponentes(Graphics g) {
        for (int i = 0; i < this.lstItems.size(); i++) {
            Item auxComponente = new Item();
            auxComponente = this.lstItems.get(i);
            g.drawImage(new ImageIcon(getClass().getResource(auxComponente.lstComponentes.getFirst().ruta)).getImage(), auxComponente.area.x, auxComponente.area.y, auxComponente.area.width, auxComponente.area.height, this);
        }
    }

    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
        this.x2Ciudad = this.ciudad.anchoCampo * this.ciudad.m;
        this.x1Componente = this.ciudad.anchoCampo * this.ciudad.m;
        repaint();
    }

    private void pintarCiudad(Graphics g) {
        for (int i = 0; i < this.ciudad.n; i++) {
            for (int j = 0; j < this.ciudad.m; j++) {
                if (!this.ciudad.matrizCiudad[i][j].equals("")) {
                    g.drawImage(new ImageIcon(getClass().getResource("../ImgComponentes/" + this.ciudad.matrizCiudad[i][j] + ".png")).getImage(), this.ciudad.anchoCampo * j, this.ciudad.altoCampo * i, this.ciudad.anchoCampo, this.ciudad.altoCampo, this);
                }
            }
        }
    }

    @Override
    public void keyTyped(KeyEvent ke) {
       }

    @Override
    public void keyPressed(KeyEvent ke) {
        if(this.itemSeleccionado.contador==this.itemSeleccionado.lstComponentes.size()-1)
        {
            this.itemSeleccionado.contador=0;
        }else 
        {
            this.itemSeleccionado.contador++;
        }
        repaint();
// throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    @Override
    public void keyReleased(KeyEvent ke) {
    }

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
